@base=http://localhost:3000

### main
GET {{base}}/ping

### login
POST {{base}}/api/auth/login


### register
POST {{base}}/api/auth/register
Content-Type: application/json

{
    "username": "mike",
    "password": "123123"
}